### ISSUE TITLE
plot_KOs_network requires the MetaNet package, but we can hardly find and install the MetaNet.

### ISSUE THREAD

**Issue by JiaLonghao1997** [Asa12138/ReporterScore#1]
plot_KOs_network requires the MetaNet package, but we can hardly find and install the MetaNet.
```R
ko_net = MetaNet::twocol_edgelist(id2ko)
ko_net = MetaNet::c_net_set(ko_net, ko_stat, vertex_class = "Significantly")
```
![image](https://github.com/Asa12138/ReporterScore/assets/32414349/6dd5558d-3158-4dde-8bf1-51a2ece92be6)

**Comment by Asa12138** [comment]
I have turned on the public access to MetaNet, and you can install it by running `plot_KOs_network` again.
By the way, it is recommended to re-install`ReporterScore` and `pcutils` from github, because I have some updates recently.
Thanks for using this tool, any suggestions welcome.

**Comment by beaPhD** [comment]
Hello, I am learning your R package ReporterScore, I have a question I want to ask you, ReporterScore score plus or minus does not represent enrichment or exhaustion, but I just want to pay attention to the expression of the rising pathway, all I personally perform a pretreatment of ko abundance, is to screen out the ko that is adjusted upward in a specific group, and then carry out your subsequent correlation analysis, so as to ensure that the subsequent screened pathway is enriched, But I can't guarantee that there is anything wrong with just screening for upregulated genes

**Comment by Asa12138** [comment]
hello，

    Thanks for choosing my package. 

    For "ReporterScore score plus or minus does not represent enrichment or exhaustion", I mentioned that this is the feature of classic RSA ('mixed' mode in my package). If you want to pay attention to the expression of the rising pathway, you can just choose the 'directed' mode, and the plus score indicating the increasing pathways.

    For more details, see ?ReporterScore::reporter_score(). I will updated my gitbub README soon.

    By the way, I do not recommend any pre-filtering for your ko table as ReporterScore are calculated using the background distribution of all kos.

    Good luck with your analysis.

2023-09-23 15:49:04beaPhD ***@***.***>wrote:




Hello, I am learning your R package ReporterScore, I have a question I want to ask you, ReporterScore score plus or minus does not represent enrichment or exhaustion, but I just want to pay attention to the expression of the rising pathway, all I personally perform a pretreatment of ko abundance, is to screen out the ko that is adjusted upward in a specific group, and then carry out your subsequent correlation analysis, so as to ensure that the subsequent screened pathway is enriched, But I can't guarantee that there is anything wrong with just screening for upregulated genes
