### ISSUE TITLE
2024 KEGG

### ISSUE THREAD

**Issue by ly-318** [Asa12138/ReporterScore#10]
My annotation results are based on KEGG 2024, and I would like to know how to update my KOlist. What specific files do I need to download for this purpose? Additionally, aside from the KOlist, are there any other components that require updating, such as using the function update_htable(type = "pathway")?

> KO_pathway <- up_level_KO(AMG_RPKM, level = "pathway", show_name = TRUE)
==================================load KOlist===================================
================KOlist download time: 2023-07-28 14:07:08.466916================
If you want to update KOlist, use `update_KO_file()`

**Comment by Asa12138** [comment]
You can use `update_KEGG` to update all components to the latest version (including KO_file, KO_htable, Pathway_htable, Module_htable, and Compound_htable).

But KEGG do not keep repository of older databases at all, at least not for users (<https://www.kegg.jp/kegg/docs/relnote.html>). It is hard to use a specific release for analysis.
