### ISSUE TITLE
ERROR in devtools::install_github('Asa12138/ReporterScore',dependencies=T) on Windows 

### ISSUE THREAD

**Issue by xzzzwj** [Asa12138/ReporterScore#2]
When I was installing this package, I encountered the following error.
* installing *source* package 'ReporterScore' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/Lenovo/AppData/Local/Temp/RtmpSAod0D/R.INSTALL70b86d2863f/ReporterScore/R/calculation.R:576:25: unexpected input
575:     replace=FALSE
576:     temp=sapply(1:perm, \
                             ^
ERROR: unable to collate and parse R files for package 'ReporterScore'
* removing 'D:/Bioinformatics/R-4.0.3/library/ReporterScore'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/Lenovo/AppData/Local/Temp/Rtmp2fp4C2/file72681adf3817/ReporterScore_1.0.0.tar.gz’ had non-zero exit status
<img width="705" alt="09451a2d4436e1b1ff02ed9154f1e91" src="https://github.com/Asa12138/ReporterScore/assets/153051179/dba18280-a395-4cf5-8a69-4abc33622192">

**Comment by Asa12138** [comment]
R version > 4.1.0 is required for installation.
