### ISSUE TITLE
plot_report_bar()的facet_level问题

### ISSUE THREAD

**Issue by Brynnhildr** [Asa12138/ReporterScore#3]
作者你好！
很高兴能使用你开发的*ReprotScore*包，这真的带来了很大的便利。使用```plot_report_bar()```画出来的图十分优美，但是我在个性化的定制中遇到了一个小问题：这个函数有没有一个参数是能够选择最后展示出来的```faceet_level```的？拿**ReadMe**中的示例数据来说，我最后只想展示*Metabolism*这一水平下的通路，其余类似*Human Disease*、*Celluar Process*等我不想呈现在图中，有没有一种方法能够实现呢？

期待您的回复！

**Comment by Asa12138** [comment]
暂时没有提供方便的参数进行筛选，可以用两种方式筛选：
1. 筛选reporter_res

```
library(dplyr)
Pathway_htable <- load_Pathway_htable()
reporter_res2 <- dplyr::left_join(reporter_res$reporter_s, Pathway_htable, by = c("ID"="Pathway_id"))
#然后就可以根据level筛选了
reporter_res2=filter(reporter_res2,level1_name=="Metabolism")
plot_report_bar(reporter_res2, rs_threshold = c(-2.5, 2.5), facet_level = TRUE)
```

2.筛选ggplot产生的图对象

```
plot_report_bar(reporter_res, rs_threshold = c(-2.5, 2.5), facet_level = TRUE)->p
p
p$data=filter(p$data,facet_level=="Metabolism")
p
```

**Comment by Brynnhildr** [comment]
> 暂时没有提供方便的参数进行筛选，可以用两种方式筛选：
> 
> 1. 筛选reporter_res
> 
> ```
> library(dplyr)
> Pathway_htable <- load_Pathway_htable()
> reporter_res2 <- dplyr::left_join(reporter_res$reporter_s, Pathway_htable, by = c("ID"="Pathway_id"))
> #然后就可以根据level筛选了
> reporter_res2=filter(reporter_res2,level1_name=="Metabolism")
> plot_report_bar(reporter_res2, rs_threshold = c(-2.5, 2.5), facet_level = TRUE)
> ```
> 
> 2.筛选ggplot产生的图对象
> 
> ```
> plot_report_bar(reporter_res, rs_threshold = c(-2.5, 2.5), facet_level = TRUE)->p
> p
> p$data=filter(p$data,facet_level=="Metabolism")
> p
> ```

好的，感谢您回复的方法，其中筛选ggplot2的图对象方法即简便又好用！再次感谢！
