### ISSUE TITLE
用directed模式，P值矫正问题

### ISSUE THREAD

**Issue by shihai-gong** [Asa12138/ReporterScore#4]
作者你好：
我注意到在pvalue2zs函数用directed模式将KO差异检验后的P值校正后/2，然后再进行了一遍矫正得到res.dt$p.adjust，然后zs <- stats::qnorm(1 - (res.dt$p.adjust)) 计算Z值。然而res.dt$p.adjust可能是1，导致zs为0，后续计算reporter_score时 会出现0/0的情况，后续的if判断会报错。
请问对P值/2，再进行矫正是否正确，还是对输入的丰度有什么要求呢？
期待您的回复！

**Comment by Asa12138** [comment]
谢谢你的仔细！
ko.test后进行pvalue2zs，p值只会进行一次矫正的，由参数p.adjust.method1控制。
对P值/2，再进行矫正的结果和矫正对P值/2的结果是一致的，即`p.adjust(p/2)==p.adjust(p)/2`，我只是写成了前面的形式，在reporterscore算法中是符合假设的。

p.adjust可能是1，导致zs为0是无法避免的，因为reporterscore就是通过类似GSEA的排序背景来计算富集分数的。所以我选择默认p.adjust.method1=“none”，即不进行矫正，而是使用原始p值作为背景，这样出现大多数p值为1的可能性较低。

如果输入的数据实验组-对照组没有什么差异导致所有ko的p值都接近1，那我认为这种数据很难进行富集分析，即便使用其他方法如fisher.test，GSEA。

但我也有输入过这种数据，不会引起程序的报错？而是会输出warning？你可以给我看看具体的例子和报错信息吧，谢谢
<img width="643" alt="image" src="https://github.com/Asa12138/ReporterScore/assets/76582179/b458c766-91eb-4bb6-9450-9cc3fe62bd55">

**Comment by shihai-gong** [comment]
我发现我所有的P值都不显著，校正后都是1，导致所有的zs值都是0，我认为是数据问题产生的错误。

**Comment by Asa12138** [comment]
> 我发现我所有的P值都不显著，校正后都是1，导致所有的zs值都是0，我认为是数据问题产生的错误。

是的，这样的数据你可以根据实验设计考虑换一些统计检验方法，"t.test", "wilcox.test", "kruskal.test", "anova", "pearson", "kendall", "spearman", "lm"等，或许结果会好一些
