### ISSUE TITLE
#Error in check_kodf_modulelist in R 

### ISSUE THREAD

**Issue by YoungerRen** [Asa12138/ReporterScore#5]
when i used Reporter Score by the usage, there was error in R:
##Error in check_kodf_modulelist(kodf, type, feature, modulelist, verbose,  : 
  All your kos do not exist in the modulelist! Please check your input table and modulelist (or  parameters `feature` and `type`).

My code was the follwing:

library(devtools)
library(ReporterScore)
df <- read.table("r1234.csv",header = T, sep = "\t")
group <- read.table('kogroup.txt',sep = ' ', header = T)
KOlist <- load_KOlist()

cat("Comparison: ",levels(factor(group$group)), "\n")
reporter_score_res=reporter_score(df,"group",group, mode="mixed",
                                  method = "anava", 
                                  type = "pathway", feature = "ko")

then , i checked the KOlist$pathway     
View(KOlist[["pathway"]])
![image](https://github.com/Asa12138/ReporterScore/assets/166517548/2623df25-627d-4abb-8ee4-5e00973a0258)
i thought it was ok,, and i checked the input table, its format was standard as your example, 
![image](https://github.com/Asa12138/ReporterScore/assets/166517548/99da419e-1bbe-4de1-a7d9-03da7fd34233)
So, i did not know the problem accur in my operation, and also could not solve it. 

  Could it be caused by the mismatching between  ko_number in my input table and KOs in KOlist$pathway, because there is only one number in ko_number column of my input table, but more than one ko_number in KOs column of KOlist$pathway? 

hope ur anwser, sincerely!

**Comment by Asa12138** [comment]
Thanks for using my package 🙏
This is a simple formatting problem, my example data is:

```
data("KO_abundance_test")
head(KO_abundance[, 1:6])
#>                WT1         WT2         WT3         WT4         WT5         WT6
#> K03169 0.002653545 0.005096380 0.002033923 0.000722349 0.003468322 0.001483028
#> K07133 0.000308237 0.000280458 0.000596527 0.000859854 0.000308719 0.000878098
#> K03088 0.002147068 0.002030742 0.003797459 0.004161979 0.002076596 0.003091182
#> K03530 0.003788366 0.000239298 0.000445817 0.000557271 0.000222969 0.000529624
#> K06147 0.000785654 0.001213630 0.001312569 0.001662740 0.002387006 0.001725797
#> K05349 0.001816325 0.002813642 0.003274701 0.001089906 0.002371921 0.001795214
```

You can see the rownames are feature ids (e.g. “K00001” (KEGG K number) if feature=“ko”; “PEX11A” (gene symbol) if feature=“gene”; “C00024” (KEGG C number) if feature=“compound”).

Instead of having a column of KO_id, you just need to change the KO_id column to the rowname to do the next step:

```
df=tibble::column_to_rownames(df,"KO_id")
```

**Comment by YoungerRen** [comment]
oh, got it! i solved it, but another problem occured on my operation.
the R console showon that there was an error in ko.test: too less common samples. did it mean my data can not be analyzed by the ReportScore?
![image](https://github.com/Asa12138/ReporterScore/assets/166517548/df83b0e6-48c6-4282-8ba0-a305ee811c25)

**Comment by Asa12138** [comment]
please refer to the usage part1: inputdata.

the group table (metadata) should have rownames, and these rownames should match the colnames of KO_df, so that this function can know the group of each sample:
```
head(metadata)
#>     Group Group2
#> WT1    WT     G3
#> WT2    WT     G3
#> WT3    WT     G3
#> WT4    WT     G3
#> WT5    WT     G3
#> WT6    WT     G1
```

**Comment by YoungerRen** [comment]
ok, i solved it, and thank u very much. this package is very nice!!!!!

**Comment by YoungerRen** [comment]
hello, when i did uplevel the KOs, there was some errors occuring on my R, i want draw a heatmap or histogram of the  KEGG_level3 pathway in different sample, my codes was as followed:
![image](https://github.com/Asa12138/ReporterScore/assets/166517548/6b186a62-9f4b-46b1-8fbc-7c1decbc58ca)
did i do something wrong? 
hope ur anwser, thanks!!

**Comment by Asa12138** [comment]
This is because the KEGG database contains "Pathway ", "Brite Hierarchies", "Not Included in Pathway or Brite", so different level3_id may correspond to the same level3_name. For example, 03041 and map03040 are both "Spliceosome".

Set show_name=FALSE so you can get a table with the row name level3_id:
```
path2name <- load_KO_htable()%>%.[, paste0("level3", c("_id", "_name"))]%>%dplyr::distinct()
KO_level3 <- up_level_KO(KO_abundance, level = "level3", show_name = F)
path2name$level3_name <- make.unique(path2name$level3_name)
rownames(KO_level3)=path2name[match(rownames(KO_level3),path2name$level3_id),"level3_name"]
```

But I recommend you to uplevel to pathway:
```
KO_pathway<- up_level_KO(KO_abundance, level = "pathway", show_name = T)
```
