### ISSUE TITLE
更新KEGG报错：错误于gzfile(file, mode): 无法打开链结

### ISSUE THREAD

**Issue by mmy333** [Asa12138/ReporterScore#6]
作者你好，很感谢你们开发的这个包，对我的帮助非常大，但我在更新KEGG时遇到以下报错无法解决，期待您的回复！！！
> update_org_pathway(
+   org = "hsa",
+   RDS_file = NULL,
+   download = TRUE,
+   download_dir = 'D:/R2'
+ )
=======================get pathway of 'hsa' from 'KEGG'.========================

total 359 pathways
===================get each pathway information from 'KEGG'.====================

50 pathways done.
100 pathways done.
150 pathways done.
200 pathways done.
250 pathways done.
300 pathways done.
350 pathways done.
错误于gzfile(file, mode): 无法打开链结
此外: 警告信息:
In gzfile(file, mode) :
  无法打开压缩文件'D:/R2/hsa_2024-09-13 09:10:33.190336.RDS'，可能是因为'Invalid argument'

**Comment by Asa12138** [comment]
你好，请查看一下本地有无D:/R2/hsa_2024-09-13 09:10:33.190336.RDS这个文件。 @mmy333 
如果有的话，尝试update_org_pathway(org = "hsa", RDS_file ='D:/R2/hsa_2024-09-13 09:10:33.190336.RDS')即可。

我刚刚本地尝试了一下，这个函数没有问题。

**Comment by mmy333** [comment]
作者你好，我想请问一下更新KEGG时需要准备什么文件以及如何准备，因为我设定的download_dir = 'D:/R2'是文件夹，直接运行以上函数时‘hsa_2024-09-13 09:10:33.190336.RDS’是自动生成的，当我指定到某一已存在的文件，会相同报错并警告：1.该文件已存在；2错误于gzfile(file, mode): 无法打开链结

**Comment by Asa12138** [comment]
不需要你自己准备的。
1. update_org_pathway会通过KEGG API逐个爬取最新的通路数据，保存为hsa_XXX.RDS
2. 读取hsa_XXX.RDS，同步到软件包内部，使用`load_org_pathway(org = "hsa")->hsa_pathway`就可以看见更新的时间了

如果你已经存在了hsa_XXX.RDS这个文件，说明第一步已经执行完了，只需要`update_org_pathway(org = "hsa", RDS_file ='D:/R2/hsa_2024-09-13 09:10:33.190336.RDS',download = F)`即可。

你可以读取一下这个文件readRDS('D:/R2/hsa_2024-09-13 09:10:33.190336.RDS')看看是否可以正常读取

**Comment by mmy333** [comment]
但是当我运行代码时并没有在文件夹中生成hsa_XXX.RDS文件，可能因此在读取该文件的时候产生了报错，无法生成RDS文件该怎么解决呢
代码如下
update_org_pathway(
  org = "hsa",
  RDS_file = NULL,
  download = TRUE,
  download_dir = 'D:/R2'
)

**Comment by Asa12138** [comment]
你好，请运行`saveRDS(list(a=1),file = "D:/R2/test.RDS")`测试一下你的R能否正常储存文件，可能是你的R的问题。

另外，保存中间文件hsa_XXX.RDS不是必须的，只是方便保留不同版本的数据库留档（因为KEGG不开放旧版本），你可以用：
```
update_org_pathway(
org = "hsa",
RDS_file = NULL,
download = FALSE
)
```
应该能更新成功

**Comment by mmy333** [comment]
我的R可以正常储存文件，可能是其他问题造成的，但我现在更新成功了，十分感谢！！！

**Comment by Asa12138** [comment]
我找到原因了😂，windows系统文件路径不能有冒号，但macOS和linux都没有这个问题，我会修改的，请更新最新版
`install_github("Asa12138/ReporterScore")`
谢谢你的反馈！
