### ISSUE TITLE
数据库怎么选

### ISSUE THREAD

**Issue by zsl0110** [Asa12138/ReporterScore#7]
你好，我有注意到在更新kolist时默认选择org=‘hsa’，如果是做微生物群落的数据应该如何选择org更符合真实情况呢

**Comment by Asa12138** [comment]
<https://github.com/Asa12138/ReporterScore?tab=readme-ov-file#ko-pathway>
microbiome的话，type=pathway即可哦，这样使用的是整个KEGG数据库。hsa的话相当于是一个子集。
