### ISSUE TITLE
reporter_score值为NAN，if (reporter_score > 0) 报错

### ISSUE THREAD

**Issue by shihai-gong** [Asa12138/ReporterScore#8]
作者你好：
宏基因组数据在使用特定基因集当背景集的时候，会出现modulelist中某一ko包含的KO数与丰度表的KO相同时，算mean_sd时抽样数与总个数一致，导致抽样1000次的结果一致，标准差为0，计算reporter_score出现0/0的情况。这样的情况会考虑兼容吗？或者不应该用特定基因集当作背景基因集。

**Comment by Asa12138** [comment]
嗯嗯，这是一个好问题。
当用户输入的总KO与某一个通路内的KO数完全重叠或者被包含时，就是说用户只输入了一个通路内KO。对于这条通路而言，它是没有任何背景的，这样是无法计算出真实的ReporterScore，富集也没有意义。

感谢您的反馈，我会修改这个报错，让这种通路的结果为NA，并保证其他通路可以计算成功。

**Comment by shihai-gong** [comment]
我看新发布的版本似乎并没有兼容clean.KO和KOnum相等的情况，由于我用的自定义的modulelist，因此min_exist_KO = 3, max_exist_KO = 600不太适用于该情况。

**Comment by Asa12138** [comment]
min_exist_KO = 3, max_exist_KO = 600应该根据你的modulelist调整即可。

clean.KO和KOnum相等的情况，可以用以下代码测试：
```
data("KO_abundance_test")
test_KOs=get_KOs(map_id = "map00010")
test_KO_abundance=KO_abundance[rownames(KO_abundance)%in%test_KOs,]
KOlist <- load_KOlist()
test_db=KOlist[["pathway"]][1,]
test_res <- reporter_score(test_KO_abundance, "Group", metadata,modulelist = test_db)
View(test_res$reporter_s)
```
正常的话结果ReporterScore就是NA
