### ISSUE TITLE
consultation

### ISSUE THREAD

**Issue by haitianyisee** [Asa12138/ReporterScore#9]
When I use your example code,it showed a bug
"> GOlist <- load_GOlist()
Not find GOlist, please run `update_GOlist()` first!
> # 4. GO-gene database
> update_GOlist()
Error in update_GOlist() : Please set download_dir when GO_file is NULL."
How to solve it?

**Comment by Asa12138** [comment]
Please set the download _ dir as the path to one of your own computers, because this function downloads the larger GO database file
